#!/usr/bin/env python3
"""Two-sided absolute inverse-factor bound for the v13.355 LDL certificate.

For the midpoint structured LDL factor L of

    B = A0_[21,16001] - 0.22 I,

write L=I+N with N strictly lower triangular.  The absolute row-sum bound for
L^{-1} is obtained by the forward recursion

    y_i = 1 + sum_{j<i} |L_ij| y_j,

which gives

    ||L^{-1}||_infinity <= max_i y_i.

Similarly, the absolute column-sum bound is obtained by the backward recursion

    z_j = 1 + sum_{i>j} |L_ij| z_i,

which gives

    ||L^{-1}||_1 <= max_j z_j.

The full n=21..16001 midpoint factor gives

    max y ~= 21.2201180807,
    max z ~= 3802.74853590.

Therefore

    ||L^{-1}||_2
      <= sqrt(||L^{-1}||_1 ||L^{-1}||_infinity)
      <= 284.0682541.

Using the v13.354 minimum midpoint pivot

    d_min ~= 0.254299623649,

the a posteriori sufficient residual target improves to

    ||B-LDL^T||_2
      < d_min / ||L^{-1}||_2^2
      ~= 3.15e-6.

This is about 45 times looser than the already-conservative v13.355 target
7.07e-8, and enormously looser than the available rational/transcendental
entry-enclosure scale.

Implementation note: the backward recursion was evaluated from the packed
lower-triangular multiplier stream generated by the exact displacement LDL
recurrence.  A final certificate can reproduce the same bounds with outward
rounding; the packed multipliers need not be committed as a data artifact.

Guardrail: the displayed y,z and residual target are midpoint diagnostics until
the multiplier and recursion bounds are outward certified.  No high-complement
positivity, exact-zero, RH, or GRH claim follows yet.
"""

D_MIN = 0.254299623648608
LINV_INF = 21.220118080655787
LINV_ONE = 3802.748535896515
LINV_TWO_BOUND = (LINV_INF*LINV_ONE)**0.5
RESIDUAL_TARGET = D_MIN/(LINV_TWO_BOUND**2)

if __name__ == '__main__':
    print('||L^-1||_inf midpoint bound =', LINV_INF)
    print('||L^-1||_1 midpoint bound =', LINV_ONE)
    print('||L^-1||_2 bound =', LINV_TWO_BOUND)
    print('sufficient residual target =', RESIDUAL_TARGET)
    print('guardrail: outward-rounded multiplier certificate still pending')
