#!/usr/bin/env python3
"""Fail-closed scaffold for a reproducible M=16001 gamma_n replay.

This supersedes the hard-coded outward radii in the v13.508 helper.  Every
accepted radius must be produced from an operation count, a magnitude/norm
bound, and the standard floating-point gamma_k = k*u/(1-k*u).  No empirical
double/long-double discrepancy and no manually chosen safety multiplier is an
accepted certificate input.

The present file records the exact obligations and implements the elementary
gamma algebra.  It intentionally FAILS until the four stage-specific magnitude
transcripts are emitted by the numerical replay itself.
"""
from decimal import Decimal, getcontext
getcontext().prec=80
D=Decimal

U64=D(2) ** D(-64)  # x86 long-double unit roundoff used by the prior replay
NF=7991
D7=7
D10=10
REMOTE_ROWS=(2_000_000-16003)//2+1


def gamma(k:int,u=U64):
    ku=D(k)*u
    if ku >= 1: raise ArithmeticError('gamma_k undefined: k*u >= 1')
    return ku/(1-ku)


def dot_abs_error(k:int,abs_product_sum):
    """|fl(x^T y)-x^T y| <= gamma_k sum_i |x_i y_i|."""
    return gamma(k)*D(str(abs_product_sum))


def gram_entry_error(k:int,abs_product_sum):
    return dot_abs_error(k,abs_product_sum)


def matmul_frobenius_from_entry(entry_radius,rows,cols):
    # ||E||_2 <= ||E||_F <= sqrt(rows*cols) max_ij |E_ij|.
    return (D(rows*cols).sqrt())*D(str(entry_radius))

# These must be generated by executable replay code, not filled from observed
# discrepancies or guessed safety factors.
TRANSCRIPT={
    'finite_ldl': None,       # pivot lower bounds, generator/RHS magnitudes, residual abs-product sums
    'finite_schur': None,     # |A_CF|, |X| and each dot abs-product sum for 10x10 formation
    'qn_formation': None,     # normalized P/N multiplication abs-product sums
    'remote_gram': None,      # per-chunk max sum |R_ki R_kj| + chunk accumulation magnitudes
    'far_moments': None,      # each moment sum abs-product magnitude and final envelope arithmetic
}


def require_transcript():
    missing=[k for k,v in TRANSCRIPT.items() if v is None]
    if missing:
        raise RuntimeError(
            'FAIL-CLOSED: missing derived magnitude transcripts: '+', '.join(missing)
        )

if __name__=='__main__':
    print('u =',U64)
    print('gamma_7991 =',gamma(NF))
    print('remote row count =',REMOTE_ROWS)
    print('gamma_remote_rows =',gamma(REMOTE_ROWS))
    require_transcript()
