#!/usr/bin/env python3
"""Primitive-arithmetic audit gate for the M16001 R_F certificate.

The v13.514 transcript correctly charges the 7991-term reductions once the
nominal A0_FF, A_FC and X payloads are present.  This gate records the remaining
primitive operations that must also be outward charged before that residual can
be consumed by a theorem-level seven-plane replay.

No guessed radius is accepted.  Missing primitive transcripts fail closed.
"""
from decimal import Decimal, getcontext
getcontext().prec=80
D=Decimal
U=D(2)**D(-64)
N=7991
NRHS=10
NENT=N*NRHS

def gamma(k):
    ku=D(k)*U
    if ku>=1: raise ArithmeticError
    return ku/(1-ku)

# Each record must be generated by the executable source-faithful replay.
# Required fields are deliberately explicit so that a later checker cannot
# silently substitute an empirical discrepancy.
REQUIRED={
 'offblock_FF_entry_formation': None, # numerator n*Zi-m*Zj; n^2-m^2; division; 2/pi scale
 'offblock_FC_entry_formation': None, # same, 7991x10
 'pole_FC_outer_formation': None,     # 2*cF*cC and addition to A0_FC
 'diag_payload_conversion': None,     # nominal diagonal -> longdouble representation radius
 'source_payload_conversion': None,   # Z,c,pi nominal payload -> longdouble representation radii
 'X_payload_conversion': None,        # computed X -> longdouble representation radius / provenance
 'frobenius_square_products': None,   # (|R|+E)^2 rounding bound
 'frobenius_sum': None,               # 79910-term nonnegative accumulation bound
 'frobenius_sqrt': None,              # outward sqrt endpoint or algebraic upper surrogate
}

def fail_closed():
    miss=[k for k,v in REQUIRED.items() if v is None]
    if miss:
        raise RuntimeError('FAIL-CLOSED primitive residual gaps: '+', '.join(miss))

if __name__=='__main__':
    print('u =',U)
    print('gamma_7991 =',gamma(N))
    print('gamma_79910 =',gamma(NENT))
    print('residual entries =',NENT)
    fail_closed()
