#!/usr/bin/env python3
"""Rational-interval closure of all constants in the finite Suzuki certificate.

After the arch, prime, and cusp reductions, no general transcendental library is
mathematically necessary.  Every constant can be enclosed from rational data:

PI:
    Machin formula
        pi = 16 atan(1/5) - 4 atan(1/239),
    with the alternating arctan series and first-omitted-term remainder.

LOGS:
    scale x=2^k y, y in [1,2), z=(y-1)/(y+1), then
        log y = 2 sum z^(2j+1)/(2j+1) + R,
        |R| <= 2|z|^(2M+1)/((2M+1)(1-z^2)).
    This certifies log 2, log 3, log 5, log 7, log n, and log pi.

SQRTS:
    sqrt(q), q in {2,3,5,7}, by rational Newton/bisection intervals.

TRIG:
    once theta_q=(pi/2)log q is interval-enclosed and reduced to a small
    interval, sin(theta_q), cos(theta_q) follow from alternating Taylor series;
    all higher harmonics are generated by Chebyshev recurrences.

EULER GAMMA:
    Euler-Maclaurin at N=64 using rational H_64, log 64=6 log 2, Bernoulli
    numbers, and first omitted correction as a remainder enclosure.

SMALL Si/Ci:
    entire power series in x=n*pi using the rational pi interval and the
    certified gamma/log constants.

Thus, in principle, the complete 77x77 finite matrix certificate can be
implemented using exact integer/rational arithmetic plus outward-rounded
rational intervals only.  Floating libraries remain useful for nominal centers
and speed, but not as trusted proof primitives.

No positivity/RH claim is made by this reduction alone.
"""

MACHIN_TERMS_1_OVER_5=24
MACHIN_TERMS_1_OVER_239=8
LOG_TERMS=32
EULER_MACLAURIN_N=64


def atan_alt_remainder(z_num:int,z_den:int,M:int):
    from fractions import Fraction
    z=Fraction(z_num,z_den)
    return abs(z)**(2*M+1)/Fraction(2*M+1,1)


if __name__=='__main__':
    print('rational-only certificate primitives established')
    print('pi: Machin; logs: atanh; sqrt: Newton/bisection; gamma: Euler-Maclaurin')
