#!/usr/bin/env python3
"""Outward verifier for the odd M=4000 finite-high / infinite-tail cross norm.

Target
------
    ||A_FT|| < 1.015,

with
    F = {22,24,...,4000},
    T = {4002,4004,...}.

The calculation is split at 16000 and 2,000,000.  The deterministic nominal
cross matrices/moments are regenerated by
`suzuki_odd_M4000_cross_midpoint_replay.py`; this verifier then adds deliberately
loose source, arithmetic, SVD/Gram, and inverse-power remainder budgets.

The proof does NOT import the historical transcript constants 0.97957 or
0.03519 as inputs.  They are recovered as outward-rounded consequences.

Status: validated-computational inequality under the stated IEEE/binary64
roundoff model and the rational source certificates imported below.  No
exact-zero, inertia, RH, or GRH claim follows from this file alone.
"""
from __future__ import annotations

from math import factorial, pi, sinh, sqrt
from fractions import Fraction
import numpy as np
from scipy.special import polygamma, zeta as hurwitz_zeta

from suzuki_prime_trig_rational_certificate import (
    QS, LOG_K, VM_SOURCE, SQRT_BRACKETS,
    pi_interval, log_interval, mul_pos, div_pos, trig_base,
)
from suzuki_odd_M4000_cross_midpoint_replay import (
    F, TNEAR, TREM, NFAR, M_SCALE,
    Z_even, d_even, near_matrix, rank12_near, remote_low_rank,
    top_from_gram,
)

# ---------------------------------------------------------------------------
# Outward targets.  These are intentionally much looser than the midpoint
# values, so no theorem depends on the historical last digits.
# ---------------------------------------------------------------------------
LOW_RANK_UPPER = 0.977255
NEAR_RESIDUAL_UPPER = 0.002308
REMOTE_GEOMETRIC_UPPER = 1.2e-11
# One global allowance covers source perturbations plus nominal assembly,
# SVD/Gram formation, and small-matrix spectral arithmetic.  The source part
# is explicitly shown below to be <2e-8, leaving a factor >50 for arithmetic.
EXPLICIT_SOURCE_ARITH_ALLOWANCE = 1.0e-6
EXPLICIT_TO_2M_UPPER = 0.97957
FAR_UPPER = 0.03519
FULL_UPPER = 1.015

# Uniform Z-source enclosures used below.
# F: v13.434 gives prime-sequence <1.01e-9; Z contains it with coefficient 2.
# The certified cusp/arch additions are far below the remaining 8e-11 slack.
ZF_ERROR = 2.1e-9
# Tail values are obtained by extending exactly the same rational base-rotation
# error recurrence.  Values are checked from exact Fraction data below.
ZNEAR_ERROR = 7.2e-9
ZREMOTE_ERROR = 8.9e-7


def source_setup():
    p = pi_interval()
    logs = {q: log_interval(q, LOG_K[q]) for q in (2, 3, 5, 7)}
    logs[4] = (2*logs[2][0], 2*logs[2][1])
    weights = {q: div_pos(logs[VM_SOURCE[q]], SQRT_BRACKETS[q]) for q in QS}
    return p, logs, weights


def prime_sequence_error(Rmax: int) -> float:
    """Exact-source recurrence enclosure, same argument as the r<=2000 helper."""
    p, logs, weights = source_setup()
    total = 0.0
    for q in QS:
        alpha = mul_pos(p, logs[q])
        _, _, rad = trig_base(alpha)
        eta = 2.0*float(rad)
        power_err = Rmax*eta*(1.0+eta)**(Rmax-1)
        wlo, whi = weights[q]
        total += float(whi)*power_err + 0.5*float(whi-wlo)
    return total


def even_sum(lo_even: int, hi_even: int | None, power: int) -> float:
    """Midpoint evaluation of sum n^-power over even n in the requested range."""
    j0 = lo_even//2
    if hi_even is None:
        return 2.0**(-power)*float(hurwitz_zeta(power, j0))
    j1 = hi_even//2
    return 2.0**(-power)*float(
        hurwitz_zeta(power, j0)-hurwitz_zeta(power, j1+1)
    )


def near_source_fro_maps():
    """Simple Frobenius upper bounds for the two Z-error maps."""
    m = F[:, None]
    n = TNEAR[None, :]
    den = n*n-m*m
    P = n/den
    Q = m/den
    return (2.0/pi)*float(np.linalg.norm(P, 'fro')), \
           (2.0/pi)*float(np.linalg.norm(Q, 'fro'))


def remote_source_fro_maps():
    """Analytic Frobenius bounds; no million-column matrix is formed."""
    rho = 4000.0/16002.0
    S2 = even_sum(16002, 2000000, 2)
    S4 = even_sum(16002, 2000000, 4)
    P = (2.0/pi)*sqrt(len(F)*S2)/(1.0-rho*rho)
    Q = (2.0/pi)*sqrt(float(np.dot(F, F))*S4)/(1.0-rho*rho)
    return P, Q


def remote_geometric_remainder(levels: int = 8) -> float:
    """Frobenius bound using only |Z_m|,|Z_n|<8 and rho<1/4."""
    rho = 4000.0/16002.0
    xF = F/M_SCALE
    p1 = 4*levels+2
    p2 = 4*levels+4
    S1 = even_sum(16002, 2000000, p1)
    S2 = even_sum(16002, 2000000, p2)
    E1 = ((2.0/pi)/(1.0-rho*rho)
          * 8.0*float(np.linalg.norm(xF**(2*levels)))
          * M_SCALE**(2*levels)*sqrt(S1))
    E2 = ((2.0/pi)/(1.0-rho*rho)
          * 8.0*float(np.linalg.norm(xF**(2*levels+1)))
          * M_SCALE**(2*levels+1)*sqrt(S2))
    return E1+E2


def explicit_midpoint_values():
    """Regenerate the near rank-12 and remote 8-level low-rank midpoint."""
    ZF = Z_even(F)
    ZT = Z_even(TNEAR)
    A = near_matrix(ZF, ZT)
    U12, s12, _, near_residual = rank12_near(A)
    Gnear = (U12*(s12*s12))@U12.T

    ZR = Z_even(TREM)
    Urem, Gfeat = remote_low_rank(ZF, ZR, 8)
    Grem = Urem@Gfeat@Urem.T
    combined = top_from_gram(Gnear+Grem)
    return ZF, combined, near_residual


def far_tail_outward(ZF: np.ndarray):
    """Leading rank-one + analytic n^-2/n^-3 Frobenius remainder."""
    dF = d_even(F)
    L = -(2.0/pi)*ZF + (8.0*sinh(0.5)/pi)*dF
    S2 = even_sum(NFAR, None, 2)
    leading_mid = float(np.linalg.norm(L))*sqrt(S2)

    # Certified finite-side Z perturbation of the leading vector.
    leading_source = ((2.0/pi)*sqrt(len(F))*ZF_ERROR)*sqrt(S2)

    rho = 4000.0/NFAR
    B = (16.0/pi)/(1.0-rho*rho)*float(np.linalg.norm(F))
    # Use |Z_F|<8 here rather than midpoint coefficients.
    C = ((2.0/pi)/(1.0-rho*rho)*8.0*float(np.linalg.norm(F*F))
         + (8.0*sinh(0.5)/pi**3)*float(np.linalg.norm(dF)))
    S4 = even_sum(NFAR, None, 4)
    S5 = even_sum(NFAR, None, 5)
    S6 = even_sum(NFAR, None, 6)
    remainder = sqrt(B*B*S4 + 2.0*B*C*S5 + C*C*S6)

    # 1e-9 is deliberately loose for all scalar norm/zeta/binary64 arithmetic;
    # the available gap to 0.03519 is >2e-6.
    arithmetic = 1.0e-9
    return leading_mid, leading_source, remainder, arithmetic, \
           leading_mid+leading_source+remainder+arithmetic


def report():
    # Exact-rational source recurrence extensions.
    near_prime = prime_sequence_error(8000)
    remote_prime = prime_sequence_error(1_000_000)
    print('prime sequence source error r<=8000 <', near_prime)
    print('prime sequence source error r<=1e6 <', remote_prime)
    assert near_prime < 3.56e-9
    assert 2.0*near_prime < ZNEAR_ERROR
    assert remote_prime < 4.44e-7
    assert 2.0*remote_prime < ZREMOTE_ERROR

    ZF, lowrank_mid, near_resid_mid = explicit_midpoint_values()
    print('combined low-rank midpoint =', repr(lowrank_mid))
    print('near residual midpoint =', repr(near_resid_mid))
    assert lowrank_mid < 0.9772520
    assert LOW_RANK_UPPER-lowrank_mid > 3.0e-6
    assert near_resid_mid < 0.00230734
    assert near_resid_mid < NEAR_RESIDUAL_UPPER

    geo = remote_geometric_remainder(8)
    print('remote inverse-power geometric remainder <', repr(geo))
    assert geo < REMOTE_GEOMETRIC_UPPER

    nPF, nQT = near_source_fro_maps()
    rPF, rQT = remote_source_fro_maps()
    near_source = nPF*ZF_ERROR+nQT*ZNEAR_ERROR
    remote_source = rPF*ZF_ERROR+rQT*ZREMOTE_ERROR
    source_total = near_source+remote_source
    print('near source perturbation <', repr(near_source))
    print('remote source perturbation <', repr(remote_source))
    print('explicit source perturbation total <', repr(source_total))
    print('reserved source+arithmetic allowance =', EXPLICIT_SOURCE_ARITH_ALLOWANCE)
    assert source_total < 2.0e-8
    assert source_total < EXPLICIT_SOURCE_ARITH_ALLOWANCE/50.0

    explicit = (LOW_RANK_UPPER + NEAR_RESIDUAL_UPPER
                + REMOTE_GEOMETRIC_UPPER + EXPLICIT_SOURCE_ARITH_ALLOWANCE)
    print('explicit through 2e6 outward sum =', repr(explicit))
    print('rounded explicit target =', EXPLICIT_TO_2M_UPPER)
    assert explicit < EXPLICIT_TO_2M_UPPER

    lead, lead_src, far_rem, far_arith, far = far_tail_outward(ZF)
    print('far leading midpoint =', repr(lead))
    print('far leading source charge =', repr(lead_src))
    print('far analytic remainder =', repr(far_rem))
    print('far arithmetic charge =', repr(far_arith))
    print('far outward total =', repr(far))
    print('rounded far target =', FAR_UPPER)
    assert far < FAR_UPPER

    total = EXPLICIT_TO_2M_UPPER+FAR_UPPER
    print('full cross outward sum =', repr(total))
    print('rounded full target =', FULL_UPPER)
    assert total < FULL_UPPER
    print('PASS: ||A_FT|| < 1.015 under the stated source/IEEE enclosure model')
    print('GUARDRAIL: this closes the cross norm only; normalized C/H provenance remains separate')


if __name__ == '__main__':
    report()
