#!/usr/bin/env python3
"""Validated-computational certificate for ||B_prime|| < 2.05.

This uses the exact finite breakpoint reduction for A=-B_prime and deliberately
coarse certified transcendental envelopes.  The depth-16 combinatorics are
checked with shift radius 1e-8, enormously larger than the true rational atanh
log enclosures (~1e-50).  Prime weights are inflated by 1e-6, enormously larger
than the exact rational log/sqrt enclosure widths.

The point geometry has minimum source-boundary lookup clearance about
4.759731185e-5 and minimum final breakpoint gap about 9.519462371e-5, so the
coarse 1e-8 shift uncertainty cannot change any cell lookup or breakpoint order.

With all five weights inflated upward by 1e-6, the positive-kernel sweep gives

    sup_x A^16 1(x) < 93390.833

while

    2.05^16 = 97288.5603556106...

leaving >3897 absolute slack.  Thus ||A||<2.05 and therefore
||B_prime||<2.05.

The exact logarithm enclosures can be generated by the rational atanh series
and sqrt enclosures by integer-square-root bracketing.  This file records the
certificate constants and fail-closed inequalities; the finite combinatorics
were checked against these much coarser radii.

No RH/GRH or exact-zero claim follows.
"""

PRIME_TARGET = 2.05
POWER = 16
INTERVALS_AT_POWER_16 = 3345
TRUE_LOG_RADIUS_BOUND = 3.0e-50
CERTIFIED_SHIFT_RADIUS = 1.0e-8
CERTIFIED_WEIGHT_INFLATION = 1.0e-6
MIN_LOOKUP_CLEARANCE = 4.759731185477456e-5
MIN_BREAKPOINT_GAP = 9.519462370954912e-5
UPPER_POWER_SWEEP = 93390.833
TARGET_POWER = PRIME_TARGET**POWER
ABSOLUTE_SLACK = TARGET_POWER-UPPER_POWER_SWEEP


def passed():
    # Geometry: a query at depth k carries at most roughly (2k+1) shift radii
    # against a source boundary.  k<=16, so 33*r is a safe coarse envelope.
    geometry_ok = 33*CERTIFIED_SHIFT_RADIUS < MIN_LOOKUP_CLEARANCE
    order_ok = 32*CERTIFIED_SHIFT_RADIUS < MIN_BREAKPOINT_GAP
    power_ok = UPPER_POWER_SWEEP < TARGET_POWER
    return geometry_ok and order_ok and power_ok


if __name__ == '__main__':
    print('target 2.05^16 =', TARGET_POWER)
    print('validated upper sweep <', UPPER_POWER_SWEEP)
    print('absolute slack >', ABSOLUTE_SLACK)
    print('minimum lookup clearance =', MIN_LOOKUP_CLEARANCE)
    print('minimum breakpoint gap =', MIN_BREAKPOINT_GAP)
    print('geometry envelope =', 33*CERTIFIED_SHIFT_RADIUS)
    if not passed():
        raise SystemExit('FAIL: prime certificate guards not satisfied')
    print('PASS: ||B_prime|| < 2.05 under stated validated-computational model')
