#!/usr/bin/env python3
"""Fresh M=3999 midpoint endpoint problem for Lane A at rho=0.10.

Target endpoint
---------------
    F^-_{0.10} = A - 0.10 B_sm,
    B_sm = D_log - H.

Parity/tail layouts
-------------------
even-v:
    core   C+ = {5,7,...,23}
    buffer F+ = {25,27,...,3999}

odd-v:
    core   C- = {6,8,...,24}
    buffer F- = {26,28,...,4000}

The source-faithful pole-free off-diagonal is generated by

    A0_mn = -(2/pi)(n Z_m - m Z_n)/(n^2-m^2),

and the endpoint shift preserves displacement rank two via

    Z_n -> Z_n - rho*pi/2.

For both parities the accelerated scalar generator is

    Z_n
      = 2 A_n
        + Im psi(1/4 + i n*pi/4)
        - (-1)^n n*pi
          sum_{k>=0} exp(-2 a_k)/(a_k^2 + (n*pi/2)^2),
    a_k = 2k+1/2.

The diagonal is assembled source-faithfully from cusp + prime + the
oscillatory-weight archimedean integral, then shifted by
-rho*(log(n/4)-1/(2n)).

The parity pole is treated as an exact rank-one update after the structured
pole-free LDL solve:

    even-v: +2 c c^T,
    odd-v : -2 d d^T.

This is a midpoint diagnostic, not an interval certificate.
"""
from __future__ import annotations

import math
import numpy as np
from scipy.integrate import quad
from scipy.special import digamma, sici


RHO = 0.10
QS = np.array([2.0, 3.0, 4.0, 5.0, 7.0])
LAMBDAS = np.array([
    math.log(2.0),
    math.log(3.0),
    math.log(2.0),
    math.log(5.0),
    math.log(7.0),
])
ELLS = np.log(QS)
WEIGHTS = LAMBDAS / np.sqrt(QS)


def h_arch(t: float) -> float:
    if t == 0.0:
        return 0.25
    if abs(t) < 1.0e-7:
        return 0.25 - t/48.0 - t*t/32.0 + 7.0*t**3/11520.0
    return math.exp(-t/2.0)/(-math.expm1(-2.0*t)) - 1.0/(2.0*t)


def arch_diag(n: int) -> float:
    b = n*math.pi/2.0
    ic = quad(
        lambda t: (2.0-t)*h_arch(t),
        0.0,
        2.0,
        weight="cos",
        wvar=b,
        epsabs=2.0e-13,
        epsrel=2.0e-13,
        limit=200,
    )[0]
    is_ = quad(
        h_arch,
        0.0,
        2.0,
        weight="sin",
        wvar=b,
        epsabs=2.0e-13,
        epsrel=2.0e-13,
        limit=200,
    )[0]
    return -(ic + is_/b)


def prime_sequence(ns):
    ns = np.asarray(ns, dtype=float)
    phases = ns[:, None]*math.pi*ELLS[None, :]/2.0
    return np.sin(phases) @ WEIGHTS


def prime_diag(ns):
    ns = np.asarray(ns, dtype=float)
    k = ns*math.pi/2.0
    phases = ns[:, None]*math.pi*ELLS[None, :]/2.0
    snn = (
        (2.0-ELLS)[None, :]*np.cos(phases)
        + np.sin(phases)/k[:, None]
    )
    return -(snn @ WEIGHTS)


def cusp_diag(ns):
    ns = np.asarray(ns, dtype=float)
    si, ci = sici(ns*math.pi)
    return np.log(ns/4.0) - ci - si/(ns*math.pi)


def z_source_faithful(ns, correction_terms: int = 20):
    ns = np.asarray(ns, dtype=float)
    a_seq = prime_sequence(ns)
    psi_im = np.imag(digamma(0.25 + 1j*ns*math.pi/4.0))

    b = ns*math.pi/2.0
    parity = np.where(ns.astype(int) % 2 == 0, 1.0, -1.0)

    kk = np.arange(correction_terms, dtype=float)
    aa = 2.0*kk + 0.5
    corr = (
        np.exp(-2.0*aa)[None, :]
        /
        (aa[None, :]**2 + b[:, None]**2)
    ).sum(axis=1)

    return (
        2.0*a_seq
        + psi_im
        - parity*ns*math.pi*corr
    )


def pole_vector(ns, sector):
    ns = np.asarray(ns, dtype=float)
    k = ns*math.pi/2.0
    if sector == "even-v":
        return (
            2.0*k*math.cosh(0.5)/(k*k+0.25),
            2.0,
        )
    if sector == "odd-v":
        return (
            2.0*k*math.sinh(0.5)/(k*k+0.25),
            -2.0,
        )
    raise ValueError(sector)


def endpoint_data(ns, sign=-1):
    ns = np.asarray(ns, dtype=int)
    z = z_source_faithful(ns) + sign*RHO*math.pi/2.0
    diag = (
        cusp_diag(ns)
        + prime_diag(ns)
        + np.array([arch_diag(int(n)) for n in ns])
        + sign*RHO*(np.log(ns/4.0)-1.0/(2.0*ns))
    )
    return z, diag


def offdiag(modes1, modes2, z1, z2):
    m = np.asarray(modes1, dtype=float)[:, None]
    n = np.asarray(modes2, dtype=float)[None, :]
    num = z1[:, None]*n - m*z2[None, :]
    den = m*m - n*n

    out = np.empty_like(den)
    mask = den != 0.0
    out[mask] = (2.0/math.pi)*num[mask]/den[mask]
    out[~mask] = 0.0
    return out


def structured_ldl(modes, z, diag):
    modes = np.asarray(modes, dtype=float)
    x = modes*modes
    u = np.asarray(z, dtype=float).copy()
    v = modes.copy()
    dcur = np.asarray(diag, dtype=float).copy()

    n = len(modes)
    L = np.eye(n)
    D = np.empty(n)

    for k in range(n):
        pivot = dcur[k]
        D[k] = pivot

        if k+1 < n:
            b = (
                (2.0/math.pi)
                * (u[k]*v[k+1:] - v[k]*u[k+1:])
                / (x[k]-x[k+1:])
            )
            ell = b/pivot
            L[k+1:, k] = ell

            dcur[k+1:] -= b*ell
            u[k+1:] -= ell*u[k]
            v[k+1:] -= ell*v[k]

    return L, D


def ldl_solve(L, D, rhs):
    rhs = np.asarray(rhs, dtype=float)
    one_column = rhs.ndim == 1
    if one_column:
        rhs = rhs[:, None]

    y = rhs.copy()
    n = L.shape[0]

    for i in range(n):
        if i:
            y[i] -= L[i, :i] @ y[:i]

    y /= D[:, None]

    x = y.copy()
    for i in range(n-1, -1, -1):
        if i+1 < n:
            x[i] -= L[i+1:, i] @ x[i+1:]

    return x[:, 0] if one_column else x


def effective_core(core, buffer_, sector, sign=-1):
    modes = np.concatenate([core, buffer_])
    z, diag = endpoint_data(modes, sign=sign)

    nc = len(core)
    zc = z[:nc]
    zf = z[nc:]
    dc = diag[:nc]
    df = diag[nc:]

    C0 = offdiag(core, core, zc, zc)
    np.fill_diagonal(C0, dc)

    R0 = offdiag(core, buffer_, zc, zf)

    L, D = structured_ldl(buffer_, zf, df)

    p, alpha = pole_vector(modes, sector)
    pc = p[:nc]
    pf = p[nc:]

    C = C0 + alpha*np.outer(pc, pc)
    R = R0 + alpha*np.outer(pc, pf)

    # Sherman-Morrison about the pole-free structured buffer.
    W = ldl_solve(L, D, R.T)
    yp = ldl_solve(L, D, pf)

    q = float(pf @ yp)
    denominator = 1.0 + alpha*q

    X = W - alpha*np.outer(yp, pf @ W)/denominator

    S = C - R @ X
    S = (S + S.T)/2.0

    return {
        "S": S,
        "eigenvalues": np.linalg.eigvalsh(S),
        "polefree_pivots": D,
        "pole_woodbury_denominator": denominator,
    }


def inertia(vals, tol=1.0e-10):
    vals = np.asarray(vals)
    return (
        int(np.sum(vals < -tol)),
        int(np.sum(np.abs(vals) <= tol)),
        int(np.sum(vals > tol)),
    )


def report():
    cases = [
        (
            "even-v",
            np.arange(5, 24, 2, dtype=int),
            np.arange(25, 4000, 2, dtype=int),
        ),
        (
            "odd-v",
            np.arange(6, 25, 2, dtype=int),
            np.arange(26, 4001, 2, dtype=int),
        ),
    ]

    print("Fresh M=3999 Lane A endpoint midpoint")
    print("rho =", RHO)
    print("endpoint = A - rho B_sm")

    for sector, core, buffer_ in cases:
        out = effective_core(core, buffer_, sector)
        vals = out["eigenvalues"]
        pivots = out["polefree_pivots"]

        print("\nsector =", sector)
        print("core =", core.tolist())
        print(
            "buffer =",
            int(buffer_[0]),
            "..",
            int(buffer_[-1]),
            "dimension =",
            len(buffer_),
        )
        print(
            "pole-free buffer min LDL pivot =",
            repr(float(np.min(pivots))),
            "at mode",
            int(buffer_[int(np.argmin(pivots))]),
        )
        print(
            "pole Woodbury denominator =",
            repr(out["pole_woodbury_denominator"]),
        )
        print(
            "effective-core eigenvalues =",
            [f"{x:.12g}" for x in vals],
        )
        print("inertia (-,0,+) =", inertia(vals))

        assert np.min(pivots) > 0.0
        assert out["pole_woodbury_denominator"] > 0.0
        assert inertia(vals) == (4, 0, 6)

    print("\nPASS midpoint: both parity effective cores have inertia (4,0,6)")
    print(
        "Guardrail: midpoint only; fresh outward residual-Gram replay still "
        "required before infinite endpoint inertia is certified."
    )


if __name__ == "__main__":
    report()
