#!/usr/bin/env python3
"""Relaxed outward verifier for the frozen-8D odd normalized residual Gram.

Target
------
    H_odd < 0.225 I.

This deliberately does NOT reproduce the historical far-tail target 0.000482.
Once the independently-derived residual-map perturbation

    ||Delta Y|| < 7e-7

is available, the theorem permits a noticeably looser nominal tail budget.
We therefore certify the point-nominal residual Gram with relaxed rounded
subtargets

    H_{<=2M,point} < 0.22442,
    H_{>2M,point}  < 0.00055.

Then, for H_point = Y_point^* Y_point and
Y_exact = Y_point + Delta Y,

    ||H_exact|| <= (sqrt(||H_point||) + ||Delta Y||)^2 < 0.225.

The finite point nominal is generated by
`suzuki_odd_M4000_frozen8_highprecision_nominal.py`; exact-vs-source and
finite-solve perturbations are handled separately by
`suzuki_odd_M4000_normalized_residual_error_bound.py`.

No exact-zero, kernel, RH, or GRH conclusion follows from this file alone.
"""
from __future__ import annotations

import math
import numpy as np
from scipy.linalg import eigvalsh
from scipy.special import sici

from suzuki_odd_M4000_frozen_dyadic_Q8_L0 import Q_HEX, L0_HEX
from suzuki_odd_M4000_frozen8_highprecision_nominal import build_nominal
from suzuki_even_arch_symbolic_rational_certificate import HD_polynomials

EXPLICIT_TARGET = 0.22442
FAR_TARGET = 0.00055
Y_ERROR = 7.0e-7
FULL_TARGET = 0.225
N_FAR = 2_000_002
K = 8

QS=(2,3,4,5,7)
VM_SOURCE={2:2,3:3,4:2,5:5,7:7}
WEIGHTS=tuple(math.log(VM_SOURCE[q])/math.sqrt(q) for q in QS)
ELLS=tuple(math.log(q) for q in QS)


def horner(poly,y):
    out=np.zeros_like(y,dtype=float)
    for k in range(max(poly),-1,-1):
        out=out*y+float(poly.get(k,0))
    return out


def tail_Z_d(ns,Hp):
    ns=np.asarray(ns,dtype=float)
    H=horner(Hp,1.0/((ns/2.0)*math.pi))
    P=np.zeros_like(ns)
    for w,ell in zip(WEIGHTS,ELLS):
        P += w*np.sin(ns*math.pi*ell/2.0)
    Si,_=sici(ns*math.pi)
    Z=2.0*P+Si+2.0*H
    k=ns*math.pi/2.0
    d=2.0*k*math.sinh(0.5)/(k*k+0.25)
    return Z,d


def even_tail_sum_upper(N,p):
    # For decreasing x^{-p} on the even lattice N,N+2,...:
    # sum <= f(N) + (1/2) int_N^infty f(x) dx.
    return N**(-p) + 0.5*N**(1-p)/(p-1)


def report():
    modes,A,Z,d=build_nominal()
    mf=modes.astype(float)
    Q=np.array([[float.fromhex(x) for x in row] for row in Q_HEX])
    L0=np.array([[float.fromhex(x) for x in row] for row in L0_HEX])

    Acc=A[:10,:10]; Acf=A[:10,10:]; Aff=A[10:,10:]
    X=np.linalg.solve(Aff,Acf.T)
    solve_res=float(np.linalg.norm(Aff@X-Acf.T,2))
    assert solve_res < 1e-12

    U=Q@np.linalg.inv(L0.T)
    W=np.vstack([U,-X@U])
    p=d@W
    j=mf

    Hp,_=HD_polynomials()

    # Explicit normalized residual Gram through two million.
    G=np.zeros((8,8))
    energy_proxy=0.0

    def add_rows(R):
        nonlocal G,energy_proxy
        G += R.T@R
        energy_proxy += float(np.sum(R*R))

    # Near band: exact Cauchy formula at the point nominal.
    for start in range(4002,16001,1000):
        stop=min(16000,start+998)
        t=np.arange(start,stop+1,2,dtype=float)
        Zt,dt=tail_Z_d(t,Hp)
        den=t[:,None]**2-j[None,:]**2
        B=(2.0/math.pi)*(j[None,:]*Zt[:,None]-t[:,None]*Z[None,:])/den
        B += 2.0*dt[:,None]*d[None,:]
        add_rows(B@W)

    # Remote band: eight inverse-power levels.
    M=np.array([(j**(2*k+1))@W for k in range(K)])
    N=np.array([((j**(2*k))*Z)@W for k in range(K)])
    for start in range(16002,2_000_001,200000):
        stop=min(2_000_000,start+200000-2)
        t=np.arange(start,stop+1,2,dtype=float)
        Zt,dt=tail_Z_d(t,Hp)
        y=1.0/t
        R=np.zeros((len(t),8))
        for k in range(K):
            R += (2.0/math.pi)*(
                Zt[:,None]*(y**(2*k+2))[:,None]*M[k]
                -(y**(2*k+1))[:,None]*N[k]
            )
        R += 2.0*dt[:,None]*p
        add_rows(R)

    G=0.5*(G+G.T)
    lam=float(eigvalsh(G)[-1])
    print('point lambda_max(H_<=2M) =',repr(lam))
    print('point accumulated row energy =',repr(energy_proxy))

    # A-posteriori shifted-Cholesky certificate for the computed 8x8 Gram.
    # The final 1e-8 allowance is deliberately much larger than the standard
    # gamma_N dot-product error for ~1e6 rows (which is O(1e-10) here), and
    # also covers chunk summation and 8x8 formation.
    GRAM_FORMATION_ALLOWANCE=1.0e-8
    Mshift=EXPLICIT_TARGET*np.eye(8)-G
    L=np.linalg.cholesky(Mshift)
    Xi=np.linalg.solve(L,np.eye(8))
    recon=float(np.linalg.norm(Mshift-L@L.T,'fro'))
    invfro=float(np.linalg.norm(Xi,'fro'))
    factor_floor=1.0/(invfro*invfro)
    print('explicit shifted Cholesky residual =',repr(recon))
    print('explicit shifted factor floor proxy =',repr(factor_floor))
    assert energy_proxy < 1.0
    assert recon < 1e-12
    assert factor_floor > 4.0e-6
    assert GRAM_FORMATION_ALLOWANCE < factor_floor
    assert lam + GRAM_FORMATION_ALLOWANCE < EXPLICIT_TARGET

    # Bound omitted k>=8 remote inverse-power levels.  Using row norms avoids
    # any cancellation assumption.  Since rho=4000/16002<1/4, the geometric
    # remainder is extremely small.
    row=np.linalg.norm(W,axis=1)
    rho=4000.0/16002.0
    B8=(16.0/math.pi)/(1.0-rho*rho)*np.sum((j**17)*row)
    C8=(2.0/math.pi)/(1.0-rho*rho)*np.sum(np.abs(Z)*(j**16)*row)
    trunc2=(B8*B8*even_tail_sum_upper(16002,36)
            +2.0*B8*C8*even_tail_sum_upper(16002,35)
            +C8*C8*even_tail_sum_upper(16002,34))
    trunc=math.sqrt(trunc2)
    print('remote K=8 residual-map remainder <',repr(trunc))
    assert trunc < 1.1e-13

    # Far point-nominal tail.  Extract L/n and bound the remainder by
    # B/n^2+C/n^3 using row norms, |Z_n|<8, and the exact pole correction.
    Llead=-(2.0/math.pi)*(Z@W)+(8.0*math.sinh(0.5)/math.pi)*p
    Lnorm=float(np.linalg.norm(Llead))
    rho=4000.0/N_FAR
    B=(16.0/math.pi)/(1.0-rho*rho)*np.sum(j*row)
    C=(2.0/math.pi)/(1.0-rho*rho)*np.sum((j*j)*np.abs(Z)*row)
    C += (8.0*math.sinh(0.5)/math.pi**3)*float(np.linalg.norm(p))

    print('||L|| =',repr(Lnorm))
    print('far B =',repr(float(B)))
    print('far C =',repr(float(C)))
    assert Lnorm < 43.847
    assert B < 8.898e6
    assert C < 5.022e7

    # Use only outward-rounded constants from this point onward.
    Lup=43.847; Bup=8.898e6; Cup=5.022e7
    s2=even_tail_sum_upper(N_FAR,2)
    s4=even_tail_sum_upper(N_FAR,4)
    s5=even_tail_sum_upper(N_FAR,5)
    s6=even_tail_sum_upper(N_FAR,6)
    lead=Lup*math.sqrt(s2)
    err=math.sqrt(Bup*Bup*s4+2.0*Bup*Cup*s5+Cup*Cup*s6)
    far=(lead+err)**2
    print('far point Gram upper =',repr(far))
    assert far < 0.000539
    assert far < FAR_TARGET

    point_upper=EXPLICIT_TARGET+FAR_TARGET
    exact_upper=(math.sqrt(point_upper)+Y_ERROR)**2
    print('rounded point H upper =',point_upper)
    print('after ||Delta Y||<7e-7, exact H upper =',exact_upper)
    print('final slack to 0.225 =',FULL_TARGET-exact_upper)
    assert exact_upper < FULL_TARGET
    print('PASS: H_odd < 0.225 I under the stated source/IEEE enclosure model')
    print('GUARDRAIL: combine with the separately certified C_odd and delta_odd only after ledger synchronization')


if __name__=='__main__':
    report()
